<img src="logo_pytropical2.png" width="280px" align="left"></img>
<br><br><br><br><br>

## Tutorial

PyTropical is a Python package to perform tropical operations.

So far, the following few basic operations have been implemented for both Max-Plus Algebra and Min-Plus Algebra:

- Tropical sum
- Tropical multiplication
- Tropical exponentiation
- Tropical polynomials
- Tropical sum for vectors
- Tropical scalar multiplication for vectors
- Tropical sum for matrices
- Tropical scalar multiplication for matrices

<hr>

In [1]:
import math as m
import numpy as np
import networkx as nx

from pytropical.tropical_algebra import MaxPlusAlgebra, MinPlusAlgebra
from pytropical.utils import *

## Max-Plus Algebra


In [2]:
maxp = MaxPlusAlgebra()
inf = maxp.inf #inf is the additive zero

In [3]:
#tropical sum
maxp.trop_sum(2.8, 3)

3

In [4]:
#print the usual symbol for the tropical sum
maxp.trop_sum(2.8, 3, symbol=True)

2.8⨁3 = 3


In [5]:
maxp.trop_sum(2, inf, symbol=True)

2⨁-inf = 2


In [6]:
#tropical multiplication
maxp.trop_mult(90, inf)

-inf

In [7]:
maxp.trop_mult(90, inf, symbol=True)

90⨀-inf = -inf


In [8]:
#tropical exponentiation

print("2^3 = 2⨀2⨀2 = ", maxp.trop_pow(2, 3))

2^3 = 2⨀2⨀2 =  6


In [9]:
#Freshman's dream: (x⨁y)^n = x^n⨁y^n

x3 = maxp.trop_pow(2, 3)
y3 = maxp.trop_pow(3, 3)

print("(2⨁3)^3 =", maxp.trop_pow(maxp.trop_sum(2, 3), 3))
print("2^3⨁3^3 =", maxp.trop_sum(x3, y3))

(2⨁3)^3 = 9
2^3⨁3^3 = 9


In [10]:
#Tropical polynomials

p = [[1,2], [2,3], [2,4]]

maxp.trop_polynomial(p)

'1⨀x^2 ⨁ 2⨀x^3 ⨁ 2⨀x^4'

In [11]:
#Tropical sum and tropical scalar multiplication of two vectors

v = [1, 0, inf]
w = [1, 2, -90]
a = 3

print("v⨁w =", maxp.vec_trop_sum(v, w))
print("v⨀w =", maxp.vec_trop_scalar_mult(a, v))

v⨁w = [1, 2, -90]
v⨀w = [4, 3, -inf]


In [12]:
#Tropical sum of two matrices

A = np.matrix([[2,3, 5],[4,7, 7]])
B = np.matrix([[2,1, -1],[5,3, 10]])

print("A⨁B =\n", maxp.matrix_trop_sum(A, B))

A⨁B =
 [[ 2.  3.  5.]
 [ 5.  7. 10.]]


In [13]:
#Tropical scalar multiplication

a = 3
print("3⨀A =\n", maxp.matrix_trop_scalar_mult(a, A))

3⨀A =
 [[ 5.  6.  8.]
 [ 7. 10. 10.]]


## Min-Plus Algebra


In [14]:
minp = MinPlusAlgebra()
inf = minp.inf #inf is the additive zero

In [15]:
minp.trop_sum(2,3)

2

In [16]:
minp.trop_sum(2, 3, symbol=True)

2⨁3 = 2


In [17]:
minp.trop_mult(30, inf, symbol=True)

30⨀inf = inf


In [18]:
#tropical exponentiation

print("2^2 = 2⨀2 = ", minp.trop_pow(2, 2))

2^2 = 2⨀2 =  4


In [19]:
#Freshman's dream: (x⨁y)^n = x^n⨁y^n

x3 = minp.trop_pow(2, 3)
y3 = minp.trop_pow(3, 3)

print("(2⨁3)^3 =", minp.trop_pow(minp.trop_sum(2, 3), 3))
print("2^3⨁3^3 =", minp.trop_sum(x3, y3))

(2⨁3)^3 = 6
2^3⨁3^3 = 6


In [20]:
#Tropical polynomials

p = [[1,2], [2,3], [2,4]]

minp.trop_polynomial(p)

'1⨀x^2 ⨁ 2⨀x^3 ⨁ 2⨀x^4'

In [21]:
#Tropical sum and tropical scalar multiplication of two vectors

v = [1, 0, inf]
w = [1, 2, -90]
a = 3

print("v⨁w =", minp.vec_trop_sum(v, w))
print("v⨀w =", minp.vec_trop_scalar_mult(a, v))

v⨁w = [1, 0, -90]
v⨀w = [4, 3, inf]


In [22]:
#Tropical sum of two matrices

A = np.matrix([[2,3, 5],[4,7, 7]])
B = np.matrix([[2,1, -1],[5,3, 10]])

print("A⨁B =\n", minp.matrix_trop_sum(A, B))

A⨁B =
 [[ 2.  1. -1.]
 [ 4.  3.  7.]]


In [23]:
#Tropical scalar multiplication

a = 3
print("3⨀A =\n", minp.matrix_trop_scalar_mult(a, A))

3⨀A =
 [[ 5.  6.  8.]
 [ 7. 10. 10.]]


In [24]:
print_pytropical()

  _____    _______              _           _  
 |  __ \  |__   __|            (_)         | | 
 | |__) |   _| |_ __ ___  _ __  _  ___ __ _| | 
 |  ___/ | | | | '__/ _ \| '_ \| |/ __/ _` | | 
 | |   | |_| | | | | (_) | |_) | | (_| (_| | | 
 |_|    \__, |_|_|  \___/| .__/|_|\___\__,_|_| 
         __/ |           | |                   
        |___/            |_|                   
